version: '3'

services:
  app:
    image: app
    build: .
    env_file:
      - .env
    ports:
      - "5001-5005:5000"
    networks:
      - default
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure

networks:
  default:
    name: es_demo
